language: node_js
node_js:
  - "5.12"
  - "6.9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm set progress=false
  - npm install -g grunt-cli bower html-auditor
install: npm install
before_script:
  - bower install --config.interactive=false
script: grunt test
