language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
install: npm install
before_script:
  - node_modules/.bin/grunt --version
  - node_modules/.bin/bower --version
  - node_modules/.bin/bower install --config.interactive=false
  - node_modules/.bin/grunt build
  - node_modules/.bin/grunt dist
script: echo "Done!"
