# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- next

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  #  npm run semantic-release
  #  npm run build
  #  npm run build:storybook
  displayName: 'npm build storybook and publish'
- task: S3Upload@1
  inputs:
    awsCredentials: 'WFP UI-Kit'
    regionName: 'eu-west-1'
    bucketName: 'uikit.wfp.org'
    sourceFolder: './'
    globExpressions: '**'
    createBucket: true
    logRequest: true
    logResponse: true