# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - next

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm run build'

  - script: |
      npm run semantic-release
    displayName: 'npm run semantic-release'

  - script: |
      npm run build:storybook
    displayName: 'npm run build:storybook'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        PACKAGE_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
        echo "Package version"
        echo $PACKAGE_VERSION
        NPM_VERSION=${PACKAGE_VERSION//./-}
        echo $NPM_VERSION
        echo '##vso[task.setvariable variable=NPM_VAR]'$NPM_VERSION

#  - task: S3Upload@1
#    inputs:
#      awsCredentials: 'WFP UI-Kit'
#      regionName: 'eu-west-1'
#      bucketName: 'uikit.wfp.org'
#      sourceFolder: './dist'
#      globExpressions: '**'
#      targetFolder: 'cdn/$(NPM_VAR)'
#      filesAcl: 'public-read'
#      createBucket: true
#      logRequest: true
#      logResponse: true


  - task: S3Upload@1
    inputs:
      awsCredentials: 'WFP UI-Kit'
      regionName: 'eu-west-1'
      bucketName: 'uikit.wfp.org'
      sourceFolder: './docs'
      globExpressions: '**'
      targetFolder: 'next-docs'
      filesAcl: 'public-read'
      createBucket: true
      logRequest: true
      logResponse: true
