trigger:
  - master
  - next
  - hotfix/*
  - bugfix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  NPM_CACHE_FOLDER: $(Pipeline.Workspace)/.npm
jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:

  - script: >
      npx -p semantic-release
      -p @semantic-release/git
      -p semantic-release-ado
      -p @semantic-release/changelog
      semantic-release
    env: { GH_TOKEN: $(GitHubToken) }
    displayName: 'Semantic release'

  - script: echo $(nextRelease)
    displayName: 'Show next version'