--- 
pool: 
  vmImage: ubuntu-latest
steps: 
  - 
    displayName: "Install Node.js"
    inputs: 
      versionSpec: 10.x
    task: NodeTool@0
  - 
    displayName: "Cache NPM packages"
    inputs: 
      key: "npm | \"$(Agent.OS)\" | package-lock.json"
      path: $(NPM_CACHE_FOLDER)
      restoreKeys: |
          npm | "$(Agent.OS)"
          npm
    task: Cache@2
  - 
    displayName: "npm install"
    script: |
        mkdir -p $(NPM_CACHE_FOLDER)
        npm ci
  - 
    displayName: "npm run build"
    script: "npm run build\n"
  - 
    displayName: "npm run semantic-release"
    script: "npm run semantic-release\n"
  - 
    displayName: "npm run build:storybook"
    script: "npm run build:storybook\n"
  - 
    condition: "or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/next'))"
    inputs: 
      archiveFile: $(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip
      archiveType: zip
      includeRootFolder: true
      replaceExistingArchive: true
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/docs
    task: ArchiveFiles@2
  - 
    inputs: 
      ArtifactName: wfp-ui-kit-build
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      publishLocation: Container
    task: PublishBuildArtifacts@1
trigger: 
  - master
  - next
  - hotfix/*
  - bugfix/*
variables: 
  NPM_CACHE_FOLDER: $(Pipeline.Workspace)/.npm
