trigger:
  - master
  - next
  - hotfix/*
  - bugfix/*
  - alpha/*

jobs:
- job: SemanticRelease
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    NPM_CACHE_FOLDER: $(Pipeline.Workspace)/.npm
    nextRelease: unknown

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        mkdir -p $(NPM_CACHE_FOLDER)
        npm -v
        npm install
      displayName: 'npm install'

    - script: >
        npx -p semantic-release --dryRun
        semantic-release
      displayName: 'Semantic release'

    - powershell: |
        echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
      name: setOutputVar

    - script: |
        npm run build
      displayName: 'npm run optimize'

    - script: >
        npx -p semantic-release
        -p @semantic-release/git
        -p @semantic-release/changelog
        -p semantic-release-ado
        semantic-release
      env: { GH_TOKEN: $(GitHubToken) }
      displayName: 'Semantic release'

    - script: |
        npmVersionString=$(node -p "require('./package.json').version") 
        echo "##vso[build.updatebuildnumber]$npmVersionString"
      displayName: 'set build number'

