# Site settings
title: "WFP UI Docs"
email: "me@matthewmorek.com"
description: ""
baseurl: "/brand/ui" # WFP CDN
url: "https://cdn.wfp.org/" # WFP CDN
version: "v0.3.0"

exclude: ["*.sublime-*", "*.sh", "*.yml", "*.DS_*"]

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

category-list: [Design, Components, Patterns, Resources, About]

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"